/**
 * Schema introspection utilities — extracted from schema-files.ts for reuse.
 * Handles drizzle-kit pull, schema cleanup, table filtering, and array column fixes.
 */

import ts from 'typescript'
import { buildDrizzleKitConfig } from './provider-registry'

/**
 * Run `drizzle-kit pull` as a subprocess to introspect a database.
 * Returns the generated schema.ts source code and table names.
 */
export async function runDrizzleKitPull(
  connectionString: string,
  engineType = 'postgresql',
  provider?: string | null
): Promise<{ source: string; tables: string[] }> {
  const { mkdtemp, readFile, rm } = await import('node:fs/promises')
  const { tmpdir } = await import('node:os')
  const { join } = await import('node:path')
  const { execFile } = await import('node:child_process')
  const { promisify } = await import('node:util')
  const execFileAsync = promisify(execFile)

  const tempDir = await mkdtemp(join(tmpdir(), 'dk-pull-'))

  try {
    const dkConfig = await buildDrizzleKitConfig(
      connectionString,
      engineType,
      provider,
      `${tempDir}/out`
    )
    const configPath = join(tempDir, 'drizzle.config.js')
    const configContent = `module.exports = ${JSON.stringify(dkConfig, null, 2)};\n`
    await import('node:fs').then(fs => fs.writeFileSync(configPath, configContent))

    // Run drizzle-kit pull (large maxBuffer for big schemas with spinner output)
    const drizzleKitBin = join(process.cwd(), 'node_modules', '.bin', 'drizzle-kit')
    try {
      await execFileAsync(drizzleKitBin, ['pull', `--config=${configPath}`], {
        cwd: process.cwd(),
        timeout: 120000,
        maxBuffer: 10 * 1024 * 1024, // 10MB — drizzle-kit spinner produces lots of output
      })
    } catch (execErr: any) {
      // Filter out non-fatal warnings (SSL, deprecation) from the error message
      const stderrMsg = (execErr.stderr || '').replace(/\(node:\d+\) Warning:.*\n?/g, '').trim()
      const stdoutMsg = (execErr.stdout || '').trim()
      const msg = stderrMsg || stdoutMsg || execErr.message
      throw new Error(`drizzle-kit pull failed: ${msg}`)
    }

    // Read the generated schema file — drizzle-kit may output schema.ts or relations.ts etc.
    const { readdir } = await import('node:fs/promises')
    const outDir = join(tempDir, 'out')
    let schemaPath: string
    try {
      const files = await readdir(outDir)
      console.log('[drizzle-kit pull] output files:', files)
      const tsFile =
        files.find(f => f.endsWith('.ts') && !f.startsWith('relations')) ||
        files.find(f => f.endsWith('.ts'))
      if (!tsFile)
        throw new Error(
          `No .ts files generated by drizzle-kit pull (found: ${files.join(', ') || 'nothing'})`
        )
      schemaPath = join(outDir, tsFile)
    } catch (err: any) {
      if (err.code === 'ENOENT')
        throw new Error(
          'drizzle-kit pull produced no output — check your connection string and database access'
        )
      throw err
    }
    const rawSource = await readFile(schemaPath, 'utf-8')
    const source = stripTableExtras(rawSource)

    // Extract table names from export statements
    const tableRegex = /export const \w+ = (?:pgTable|sqliteTable)\("(\w+)"/g
    const tables: string[] = []
    for (let match = tableRegex.exec(source); match !== null; match = tableRegex.exec(source)) {
      tables.push(match[1])
    }

    return { source, tables }
  } finally {
    await rm(tempDir, { recursive: true, force: true }).catch(() => {})
  }
}

/**
 * Strip index/constraint/foreignKey extras from pgTable() calls.
 * drizzle-kit generates a 3rd argument `(table) => [...]` with indexes etc.
 * that can contain complex/invalid TS for exotic index types (BM25, GIN, etc).
 * We only need columns for schema definitions, so remove the extras and
 * clean up unused imports.
 */
export function stripTableExtras(source: string): string {
  let result = source
  const extraPattern = /\},\s*\(table\)\s*=>\s*\[/g
  const removals: Array<{ start: number; end: number }> = []

  for (let m = extraPattern.exec(source); m !== null; m = extraPattern.exec(source)) {
    const startOfExtras = m.index + 1 // position of the comma after `}`
    let depth = 1
    let i = m.index + m[0].length
    while (i < source.length && depth > 0) {
      if (source[i] === '[') depth++
      else if (source[i] === ']') depth--
      i++
    }
    // Skip past optional whitespace and `)`
    while (i < source.length && /\s/.test(source[i])) i++
    if (source[i] === ')') i++ // skip the closing paren of pgTable()
    removals.push({ start: startOfExtras, end: i })
  }

  // Apply removals in reverse order
  for (const { start, end } of removals.reverse()) {
    result = `${result.slice(0, start)})${result.slice(end)}`
  }

  // Clean up imports: remove unused imports that were only for indexes/constraints
  const indexOnlyImports = [
    'index',
    'uniqueIndex',
    'unique',
    'foreignKey',
    'check',
    'primaryKey',
    'pgPolicy',
  ]
  for (const imp of indexOnlyImports) {
    // Only remove if not actually used in the cleaned source (outside the import line)
    const importPattern = new RegExp(`\\b${imp}\\b`)
    const withoutImports = result.replace(/^import\s+\{[^}]+\}\s+from\s+.+$/gm, '')
    if (!importPattern.test(withoutImports)) {
      // Remove from import list
      result = result.replace(new RegExp(`,\\s*${imp}\\b|\\b${imp}\\s*,?`), '')
    }
  }

  // Also remove `import { sql } from "drizzle-orm"` if sql is no longer used
  const withoutImports = result.replace(/^import\s+\{[^}]+\}\s+from\s+.+$/gm, '')
  if (!/\bsql\b/.test(withoutImports)) {
    result = result.replace(/^import\s*\{\s*sql\s*\}\s*from\s*["']drizzle-orm["']\s*;?\s*\n?/m, '')
  }

  // Clean up empty/malformed import lines
  result = result.replace(/import\s*\{\s*\}\s*from\s*.+\n?/g, '')
  // Clean up trailing commas or spaces in import braces
  result = result.replace(/\{\s*,/g, '{').replace(/,\s*\}/g, ' }')

  return result
}

/**
 * Programmatically filter a Drizzle schema to keep only selected tables.
 * Uses the TypeScript AST to accurately identify table definitions, enum usage, and imports.
 * selectedTableSqlNames: the SQL table names the user chose (e.g. "team_invitations", "keys")
 */
export function filterSchema(source: string, selectedTableSqlNames: string[]): string {
  const keepSet = new Set(selectedTableSqlNames)
  const sf = ts.createSourceFile('schema.ts', source, ts.ScriptTarget.Latest, true)

  // 1. Identify which top-level variable declarations are pgTable/sqliteTable calls,
  //    and map their SQL name to their variable name + statement range.
  interface TableInfo {
    varName: string
    sqlName: string
    node: ts.Node
  }
  interface EnumInfo {
    varName: string
    node: ts.Node
  }

  const allTables: TableInfo[] = []
  const allEnums: EnumInfo[] = []
  const otherStatements: ts.Node[] = []
  const importStatements: ts.Node[] = []

  for (const stmt of sf.statements) {
    // Import declarations
    if (ts.isImportDeclaration(stmt)) {
      importStatements.push(stmt)
      continue
    }

    // Exported variable statements: export const x = pgTable(...) or pgEnum(...)
    if (
      ts.isVariableStatement(stmt) &&
      stmt.modifiers?.some(m => m.kind === ts.SyntaxKind.ExportKeyword)
    ) {
      const decl = stmt.declarationList.declarations[0]
      if (decl && ts.isIdentifier(decl.name) && decl.initializer) {
        const varName = decl.name.text
        const init = decl.initializer

        // Check for pgTable("name", ...) or sqliteTable("name", ...)
        if (ts.isCallExpression(init)) {
          const callee = init.expression
          const calleeName = ts.isIdentifier(callee) ? callee.text : ''

          if (
            (calleeName === 'pgTable' ||
              calleeName === 'sqliteTable' ||
              calleeName === 'mysqlTable') &&
            init.arguments.length >= 1 &&
            ts.isStringLiteral(init.arguments[0])
          ) {
            allTables.push({ varName, sqlName: init.arguments[0].text, node: stmt })
            continue
          }

          // Check for pgEnum("name", [...])
          if (
            (calleeName === 'pgEnum' ||
              calleeName === 'sqliteEnum' ||
              calleeName === 'mysqlEnum') &&
            init.arguments.length >= 1 &&
            ts.isStringLiteral(init.arguments[0])
          ) {
            allEnums.push({ varName, node: stmt })
            continue
          }
        }
      }
    }

    // Everything else (pgView, type declarations, etc.)
    otherStatements.push(stmt)
  }

  // 2. Determine which tables to keep
  const keptTables = allTables.filter(t => keepSet.has(t.sqlName))
  // 3. Get the source text of kept tables to determine which enums are referenced
  const keptTablesSrc = keptTables.map(t => source.slice(t.node.pos, t.node.end)).join('\n')
  const keptEnums = allEnums.filter(e => {
    // An enum is referenced if its variable name appears in any kept table's source
    const pattern = new RegExp(`\\b${e.varName}\\b`)
    return pattern.test(keptTablesSrc)
  })
  // Also keep "other" statements (pgView, types) that reference kept tables
  const keptOther = otherStatements.filter(stmt => {
    const text = source.slice(stmt.pos, stmt.end)
    for (const t of keptTables) {
      if (text.includes(t.varName)) return true
    }
    return false
  })

  // 4. Build the filtered source — collect kept statement source texts in original order
  const keptNodes = new Set<ts.Node>()
  for (const t of keptTables) keptNodes.add(t.node)
  for (const e of keptEnums) keptNodes.add(e.node)
  for (const o of keptOther) keptNodes.add(o)

  const bodyParts: string[] = []
  for (const stmt of sf.statements) {
    if (ts.isImportDeclaration(stmt)) continue // handled separately
    if (keptNodes.has(stmt)) {
      bodyParts.push(source.slice(stmt.pos, stmt.end).trim())
    }
  }
  const bodyText = bodyParts.join('\n\n')

  // 5. Fix imports — scan bodyText for identifiers that need to be imported
  const newImports: string[] = []
  for (const imp of importStatements) {
    if (!ts.isImportDeclaration(imp)) continue
    const moduleSpecifier = (imp.moduleSpecifier as ts.StringLiteral).text
    const namedBindings = imp.importClause?.namedBindings

    if (namedBindings && ts.isNamedImports(namedBindings)) {
      const usedNames = namedBindings.elements
        .map(e => e.name.text)
        .filter(name => {
          // Keep import if identifier is used in the body
          const pattern = new RegExp(`\\b${name}\\b`)
          return pattern.test(bodyText)
        })

      if (usedNames.length > 0) {
        newImports.push(`import { ${usedNames.join(', ')} } from "${moduleSpecifier}"`)
      }
    } else {
      // Default or namespace imports — keep as-is if referenced
      newImports.push(source.slice(imp.pos, imp.end).trim())
    }
  }

  return `${newImports.join('\n')}\n\n${bodyText}\n`
}

/**
 * Fix array columns that drizzle-kit fails to annotate with .array().
 * Queries information_schema.columns for array types (data_type = 'ARRAY')
 * and patches the schema source to add .array() where missing.
 */
export async function fixArrayColumns(
  source: string,
  drizzleDb: any,
  engineType: string
): Promise<string> {
  // Only PostgreSQL has array types
  if (engineType !== 'postgresql' && engineType !== 'postgres') return source

  try {
    const queryResult = await drizzleDb.execute(
      `SELECT table_name, column_name FROM information_schema.columns WHERE data_type = 'ARRAY' AND table_schema = 'public'`
    )
    const rows: Array<{ table_name: string; column_name: string }> = Array.isArray(queryResult)
      ? queryResult
      : queryResult.rows || []
    if (rows.length === 0) return source

    // Build a set of "tableSqlName:columnSqlName" that should have .array()
    const arrayColumns = new Set(rows.map(r => `${r.table_name}:${r.column_name}`))

    // Parse with TS AST to find table declarations and their columns
    const sf = ts.createSourceFile('schema.ts', source, ts.ScriptTarget.Latest, true)

    // Collect patches (position + insertion text) to apply in reverse order
    const patches: Array<{ pos: number; insert: string }> = []

    for (const stmt of sf.statements) {
      if (!ts.isVariableStatement(stmt)) continue
      const decl = stmt.declarationList.declarations[0]
      if (!decl?.initializer || !ts.isCallExpression(decl.initializer)) continue

      const callee = decl.initializer.expression
      const calleeName = ts.isIdentifier(callee) ? callee.text : ''
      if (!['pgTable', 'sqliteTable'].includes(calleeName)) continue
      if (decl.initializer.arguments.length < 2) continue

      const tableNameArg = decl.initializer.arguments[0]
      if (!ts.isStringLiteral(tableNameArg)) continue
      const tableSqlName = tableNameArg.text

      // Second arg is the columns object literal
      const columnsArg = decl.initializer.arguments[1]
      if (!ts.isObjectLiteralExpression(columnsArg)) continue

      for (const prop of columnsArg.properties) {
        if (!ts.isPropertyAssignment(prop)) continue

        // Get the SQL column name from the column call's first string argument,
        // or fall back to the property name (JS key)
        let columnSqlName: string | undefined
        const propName = prop.name && ts.isIdentifier(prop.name) ? prop.name.text : undefined

        // Walk the call chain to find the column type call with a string arg
        let node: ts.Node = prop.initializer
        while (ts.isCallExpression(node) || ts.isPropertyAccessExpression(node)) {
          if (ts.isCallExpression(node)) {
            // Check if this call has a string literal first arg (the SQL column name)
            if (node.arguments.length > 0 && ts.isStringLiteral(node.arguments[0])) {
              columnSqlName = node.arguments[0].text
            }
            node = node.expression
          } else {
            node = node.expression
          }
        }

        // Fall back to converting camelCase property name to snake_case
        if (!columnSqlName && propName) {
          columnSqlName = propName.replace(/[A-Z]/g, l => `_${l.toLowerCase()}`)
        }

        if (!columnSqlName) continue
        if (!arrayColumns.has(`${tableSqlName}:${columnSqlName}`)) continue

        // Check if .array() is already present in the source for this property
        const propText = source.slice(prop.pos, prop.end)
        if (propText.includes('.array()')) continue

        // Find the end of the column expression to insert .array()
        // The expression ends just before any trailing comma or whitespace
        const endPos = prop.initializer.end
        patches.push({ pos: endPos, insert: '.array()' })
      }
    }

    // Apply patches in reverse order so positions stay valid
    let patched = source
    patches.sort((a, b) => b.pos - a.pos)
    for (const { pos, insert } of patches) {
      patched = `${patched.slice(0, pos)}${insert}${patched.slice(pos)}`
    }

    return patched
  } catch (err) {
    console.error('[fixArrayColumns] Failed to query array columns, skipping fix:', err)
    return source
  }
}

/**
 * Generate a unique name for a file. Queries existing names for the connection
 * and appends -2, -3, etc. if the base name is taken.
 */
export async function autoName(
  db: any,
  table: any,
  baseName: string,
  connectionId: number,
  orgId = 1
): Promise<string> {
  const { sanitizeFileName } = await import('./filename')
  const { and, eq } = await import('drizzle-orm')
  const sanitized = sanitizeFileName(baseName)
  const existing = await db
    .select({ name: table.name })
    .from(table)
    .where(and(eq(table.connectionId, connectionId), eq(table.organisationId, orgId)))
  const names = new Set(existing.map((r: any) => r.name))
  if (!names.has(sanitized)) return sanitized
  const dot = sanitized.lastIndexOf('.')
  const [stem, ext] = dot > 0 ? [sanitized.slice(0, dot), sanitized.slice(dot)] : [sanitized, '']
  let i = 2
  while (names.has(`${stem}-${i}${ext}`)) i++
  return `${stem}-${i}${ext}`
}
